#! /bin/bash

# list of files/folders to be symlinked
# symlink will be created from source (in dotfiles repo) to destination (existing file to override)
# make sure to leave an empty line at the end of the list
# escape white spaces with \
# lines format: destination, source
#   desination - the original file on disk
#   source - the symlinked file in the dotfiles repo folder structure, relative to the repo's base dir

# example:
# ~/.bash_profile, /bash/.bash_profile
# ~/.test, /dir12/.test

# bash
~/.bash_profile, /bash/.bash_profile
~/.bashrc, /bash/.bashrc
~/.inputrc, /bash/.inputrc
~/.bash/aliases, /bash/aliases
~/.bash/aliases-osx, /bash/aliases-osx
~/.bash/functions, /bash/functions
~/.bash/prompt, /bash/prompt
~/.bash/variables, /bash/variables

# sshrc
~/.sshrc, /bash/.sshrc
~/.sshrc.d/aliases, /bash/aliases
~/.sshrc.d/functions, /bash/functions

# git
~/.gitconfig, /git/.gitconfig
~/.git/.gitignore, /git/.gitignore

# sbt
# ~/.sbt/build.sbt, /sbt/0.12/build.sbt
# ~/.sbt/plugins/plugins.sbt, /sbt/0.12/plugins.sbt
# ~/.sbt/0.13/build.sbt, /sbt/0.13/build.sbt
# ~/.sbt/0.13/plugins/plugins.sbt, /sbt/0.13/plugins.sbt

# vim
~/.vim, /vim/vim
~/.vimrc, /vim/.vimrc

# sublime
# ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings, /sublime/Preferences.sublime-settings
~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User, /sublime

# make sure to keep an empty line at the end:
