#!/bin/bash
#
# script will copy all files in $links, overriding existing symlinks and files/folders

LINKS="links"
DOTFILES=${PWD}

# validate script working directory is dotfiles dir
if [ ! -f $DOTFILES/install ]; then
  echo "*** ERROR: Make sure to run script in dotfiles dir! ***"
  exit
fi

echo "Copying files:"

while read line; do
  if [[ ! $line == \#* ]] && [ -n "$line" ]; then
    IFS=","
    set -- $line

    # dest - the file to override in ~/
    # src - the source file in the dotfiles repo
    dest=$(echo $1 | sed 's/^ *//g' | sed 's/ *$//g')
    dest=${dest/"~"/$HOME}
    src=$(echo $2 | sed 's/^ *//g' | sed 's/ *$//g')
    src=$DOTFILES$src

    # unlink
    if [ -L $dest ]; then
      unlink $dest
    fi

    # delete file
    if [ -a $dest ]; then
      rm -rf $dest
    fi

    # create dir
    mkdir -p -- "$(dirname -- "$dest")"

    # copy file
    cp -r $src $dest
    echo "$src -> $dest"
  fi
done < $LINKS
