#!/bin/bash
#
#

ssh_tunnel() {
  local HOST=$1
  local PORT=$2

  if [ -z "$HOST" ]; then
    echo "No port provided!"
    return 1
  fi

  if [ -z "$PORT" ]; then
    echo "No port provided!"
    return 1
  fi

  nc -z localhost $PORT 2> /dev/null

  if [ $? -eq 0 ]; then
    echo "${YELLOW}${BOLD}Tunnel already connected!${RESET}"
    echo ""
    return 1
  fi

  echo "${RED}${BOLD}"
  echo "   _____ __             __  _                __________ __  __   ______                       __"
  echo "  / ___// /_____ ______/ /_(_)___  ____ _   / ___/ ___// / / /  /_  __/_  ______  ____  ___  / /"
  echo "  \__ \/ __/ __ \`/ ___/ __/ / __ \/ __ \`/   \__ \\\__ \/ /_/ /    / / / / / / __ \/ __ \/ _ \/ / "
  echo " ___/ / /_/ /_/ / /  / /_/ / / / / /_/ /   ___/ /__/ / __  /    / / / /_/ / / / / / / /  __/ /  "
  echo "/____/\__/\__,_/_/   \__/_/_/ /_/\__, /   /____/____/_/ /_/    /_/  \__,_/_/ /_/_/ /_/\___/_/   "
  echo "                                /____/                                                          "
  echo "  Host: $HOST"
  echo "  Port: $PORT"
  echo "${RESET}"

  ssh -D $PORT -N $HOST
}
