#!/bin/bash
#
#

ssh_tunnel() {
  local HOST=$1
  local PORT=$2

  if [ -z "$HOST" ]; then
    echo "No host provided!"
    return 1
  fi

  if [ -z "$PORT" ]; then
    echo "No port provided!"
    return 1
  fi

  nc -z localhost $PORT 2> /dev/null

  if [ $? -eq 0 ]; then
    echo "${YELLOW}${BOLD}Tunnel already connected!${RESET}"
    echo ""
    return 1
  fi

  echo "${RED}${BOLD}"
  echo "Starting SSH tunneling:"
  echo "======================="
  echo ""
  echo "  Host: $HOST"
  echo "  Port: $PORT"
  echo "${RESET}"

  ssh -D $PORT -N $HOST
}

ssh_port_forward() {
  local HOST=$1
  local REMOTE_PORT=$2
  local LOCAL_PORT=$3

  if [ -z "$HOST" ]; then
    echo "No host provided!"
    return 1
  fi

  if [ -z "$REMOTE_PORT" ]; then
    echo "No remote port provided!"
    return 1
  fi

  if [ -z "$LOCAL_PORT" ]; then
    echo "No local port provided!"
    return 1
  fi

  nc -z localhost $LOCAL_PORT 2> /dev/null

  if [ $? -eq 0 ]; then
    echo "${YELLOW}${BOLD}Port already forwarded!${RESET}"
    echo ""
    return 1
  fi

  echo "${RED}${BOLD}"
  echo "Starting SSH port forwarding:"
  echo "============================="
  echo ""
  echo "  Host: $HOST"
  echo "  Remote port: $REMOTE_PORT"
  echo "  Local port: $LOCAL_PORT"
  echo "${RESET}"

  ssh -L $LOCAL_PORT:$HOST:$REMOTE_PORT -N $HOST
}
