#!/bin/bash
#
#

if [ $(which fortune) ]; then
  echo ""
  fortune
  echo ""
fi

export PS1="\
${BOLD}\
${GREEN}${USER}@${SHORT_HOSTNAME}${CYAN}\$(screen_info):\
${WHITE}${WORKING_DIRECTORY}\
${YELLOW}\$(scm_info) \
${PURPLE}$ ${RESET}"
