#!/bin/bash
#
#

if [ $(which fortune) ]; then
  echo ""
  fortune
  echo ""
fi

export PS1="\
${P_BOLD}\
${P_GREEN}${USER}@${SHORT_HOSTNAME}${P_CYAN}\$(session_info):\
${P_BLUE}${WORKING_DIRECTORY}\
${P_YELLOW}\$(scm_info) \
${P_BLUE}$ ${P_RESET}"
