#!/bin/bash
#
#

# User
if [ "$USER" != "$(whoami)" ]; then
  USER=$(whoami)
fi

export PATH="/usr/local/bin:/usr/local/sbin:$BASH_DIR/scripts-common:$BASH_DIR/scripts-local:$PATH"

# Use gnutar as tar, for sshrc warnings
if [ -e "/usr/local/opt/gnu-tar/libexec/gnubin/tar" ]; then
  export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
fi

# JVM
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export MAVEN_OPTS="-Xmx4g"

# For maven 3.3.9 don't set M2_HOME anymore:
# http://stackoverflow.com/questions/34015529/installing-maven-3-3-9-how-to-set-m2-home-maven-home-and-bin-folder
# if [ -f $(brew --prefix)/bin/mvn ]; then
#   export M2_HOME="$(brew --prefix)/bin/mvn"
#   export M2=$M2_HOME/bin
# fi

# FB
export ANDROID_SDK="/opt/android-sdk"
export ANDROID_NDK="/opt/android-ndk"
export ANDROID_HOME="$ANDROID_SDK"
export NDK_HOME="$ANDROID_NDK/android-ndk-r10e"
export PATH="$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$PATH"
export DEVSERVER="devvm126.prn3.facebook.com"
