#!/bin/bash
#
#

export PATH="/usr/local/bin:/usr/local/sbin:$BASH_DIR/scripts-common:$BASH_DIR/scripts-local:$PATH"
export EDITOR=vim
export VISUAL=vim

# Use gnutar as tar, for sshrc warnings
if [ -e "/usr/local/opt/gnu-tar/libexec/gnubin/tar" ]; then
  export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
fi

# Go
# export GOPATH=$HOME/Dev/go
# export PATH=$PATH:$GOPATH/bin

# JVM
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export MAVEN_OPTS="-Xmx4g -XX:PermSize=256m -Xss128M -XX:+CMSClassUnloadingEnabled"

if [ -f $(brew --prefix)/bin/mvn ]; then
  export M2_HOME="$(brew --prefix)/bin/mvn"
  export M2=$M2_HOME/bin
fi

# FB
export PATH="~/buck/bin:$PATH"
export ANDROID_SDK=/opt/android-sdk
export ANDROID_NDK=/opt/android-ndk
export ANDROID_HOME=${ANDROID_SDK}
export PATH="$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$PATH"
