#!/bin/bash
#
#

# Filesystem, navigation, terminal
alias back='cd -'                               # go back one folder
alias path='echo $PATH | tr ":" "\n" | sort'    # print $path nicely
alias ll='ls -l --time-style=+"%Y-%m-%d %H:%M:%S" --color -h -a'
alias mkdir='mkdir -p'                          # creat dirs recursively
alias ln='ln -v'                                # make ln verbose
alias ..='cd ..'                                # make .. go up a folder

# Helpers
alias grep='grep --color=auto'                  # color grep matches
alias count='wc -l'                             # count lines
alias size='du -sh'                             # get folder size
alias sizer='du -h -c'                          # get and print folder size for all folders, recursively
alias disks='df -H -l'                          # show available disk space
alias ip='ifconfig | grep "inet "'              # quickly print ip address
alias ping='ping -c 5'                          # pings with 5 packets, not unlimited

# Diff
alias quickdiff='diff --side-by-side --suppress-common-lines -W 150'
alias qdiff='git diff --no-index -- '

# HTTP/web
alias encode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
alias decode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias sniff="sudo ngrep -d 'en0' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias whois="whois -h whois-servers.net"
alias ips="ifconfig | grep 'inet ' | cut -d ' ' -f 2"
alias eip="dig +short myip.opendns.com @resolver1.opendns.com"

# Git
alias gs='git status'
alias ga='git add -A'
alias gp='git push origin HEAD'
alias gd='git difftool'
alias gc='git commit -m'
alias gl='git log -n 20 --format="%ai  %Cgreen%h%Creset  %<(10,trunc)%aN  %s"'
alias gsl='git log --decorate --graph --pretty=short'

# Mercurial
alias hl='hg log --template "{date|localdate|isodatesec}  ${GREEN}{node|short}${RESET}  ${LIGHT_PURPLE}{pad(phabdiff, 8)}${RESET}  {pad(author|emailuser, 17)}  {desc|strip|firstline}\n"'
alias hg-show-shelve='hg shelve -l -p'
alias hg-prev='hg up $(hg id -i)^1'
alias hg-next='hg up $(hg log -r "children($(hg id -i))" --template "{node|short}\n")'

# Misc
alias rand='openssl rand -hex 16'
alias randn='openssl rand -hex '
alias randb64='openssl rand -base64 16'
alias randb64n='openssl rand -base64 '
alias line='printf "%100s\n" | tr " " ='
alias unique='uniq'
alias kdiff='ksdiff'
alias checksum='md5'
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'
alias sum="xargs | tr ' ' '+' | bc"
alias tree="tree -a"

# FB
alias build='buck build @mode/mac skycastle/src/...'
alias test='buck test @mode/mac skycastle/src/...'
