#!/bin/bash
#
#

# Set terminal title
title() {
  echo -en "\033]2;$1\007";
}

# Set as executable
chmox() {
  chmod +x $1
}

# Extract (almost) any archive format
extract() {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)        tar xjf $1        ;;
      *.tar.gz)         tar xzf $1        ;;
      *.bz2)            bunzip2 $1        ;;
      *.rar)            unrar x $1        ;;
      *.gz)             gunzip $1         ;;
      *.tar)            tar xf $1         ;;
      *.tbz2)           tar xjf $1        ;;
      *.tgz)            tar xzf $1        ;;
      *.zip)            unzip $1          ;;
      *.jar)            unzip $1          ;;
      *.war)            unzip $1          ;;
      *.Z)              uncompress $1     ;;
      *)                echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# A recursive, case-insensitive grep that excludes binary files
dgrep() {
  grep -iR "$@" * | grep -v "Binary"
}

# A recursive, case-insensitive grep that excludes binary files and returns only unique filenames
dfgrep() {
  grep -iR "$@" * | grep -v "Binary" | sed 's/:/ /g' | awk '{ print $1 }' | sort | uniq
}

# Process grep
psgrep() {
  if [ ! -z $1 ] ; then
    echo "Grepping for processes matching $1..."
    ps aux | grep $1 | grep -v grep
  else
    echo "!! Need name to grep for"
  fi
}

# Kills any process that matches a regexp passed to it
killit() {
  ps aux | grep -v "grep" | grep "$@" | awk '{print $2}' | xargs sudo kill
}

# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
json() {
  if [ -t 0 ]; then # argument
    python -mjson.tool <<< "$*" | pygmentize -l javascript;
  else # pipe
    python -mjson.tool | pygmentize -l javascript;
  fi;
}

# XML syntax highlighting
xml() {
  if [ -t 0 ]; then # argument
    xmllint --format - <<< "$*" | pygmentize -l xml;
  else # pipe
    xmllint --format - | pygmentize -l xml;
  fi;
}

# HTML syntax highlighting
html() {
  if [ -t 0 ]; then # argument
    xmllint --html - <<< "$*" | pygmentize -l html;
  else # pipe
    xmllint --html - | pygmentize -l html;
  fi;
}

# Find who's using a specific port
whoport() {
  lsof -i :$1
}

# Trim a trailing newline from file
remove_trailing_newline() {
  perl -pi -e 'chomp if eof' $1
}

# TODO: What does this do?
hg-log-user() {
  if [[ "$1" == *@fb.com ]]; then
    hg log --user $1
  else
    hg log --user "$1@fb.com"
  fi
}

# User python simple http server to serve a directory
servethis() {
  local port=$1
  if [ -z "$port" ]; then
    port=8080
  fi

  python -m SimpleHTTPServer $port
}
