#!/bin/bash
#
#

NEW_LINE="\n"
WORKING_DIRECTORY="\w"
HOSTNAME=$(hostname)
SHORT_HOSTNAME="\h"
DATE_TIME="\D{%F %T}"

P_RESET="\[$(tput sgr0)\]"
P_BOLD="\[$(tput bold)\]"
P_UNDERLINE="\[$(tput smul)\]"
P_NO_UNDERLINE="\[$(tput rmul)\]"
P_BLINK="\[$(tput blink)\]"
P_REVERSE="\[$(tput rev)\]"

P_BLACK="\[$(tput setaf 0)\]"
P_RED="\[$(tput setaf 1)\]"
P_GREEN="\[$(tput setaf 2)\]"
P_YELLOW="\[$(tput setaf 3)\]"
P_BLUE="\[$(tput setaf 4)\]"
P_PURPLE="\[$(tput setaf 5)\]"
P_CYAN="\[$(tput setaf 6)\]"
P_WHITE="\[$(tput setaf 7)\]"

P_LIGHT_BLACK="\[$(tput setaf 8)\]"
P_LIGHT_RED="\[$(tput setaf 9)\]"
P_LIGHT_GREEN="\[$(tput setaf 10)\]"
P_LIGHT_YELLOW="\[$(tput setaf 11)\]"
P_LIGHT_BLUE="\[$(tput setaf 12)\]"
P_LIGHT_PURPLE="\[$(tput setaf 13)\]"
P_LIGHT_CYAN="\[$(tput setaf 14)\]"
P_LIGHT_WHITE="\[$(tput setaf 15)\]"

P_BG_BLACK="\[$(tput setab 0)\]"
P_BG_RED="\[$(tput setab 1)\]"
P_BG_GREEN="\[$(tput setab 2)\]"
P_BG_YELLOW="\[$(tput setab 3)\]"
P_BG_BLUE="\[$(tput setab 4)\]"
P_BG_PUEPLE="\[$(tput setab 5)\]"
P_BG_CYAN="\[$(tput setab 6)\]"
P_BG_WHITE="\[$(tput setab 7)\]"

P_BG_LIGHT_BLACK="\[$(tput setab 8)\]"
P_BG_LIGHT_RED="\[$(tput setab 9)\]"
P_BG_LIGHT_GREEN="\[$(tput setab 10)\]"
P_BG_LIGHT_YELLOW="\[$(tput setab 11)\]"
P_BG_LIGHT_BLUE="\[$(tput setab 12)\]"
P_BG_LIGHT_PURPLE="\[$(tput setab 13)\]"
P_BG_LIGHT_CYAN="\[$(tput setab 14)\]"
P_BG_LIGHT_WHITE="\[$(tput setab 15)\]"

# Get tmux/screen session info
session_info() {
  if [[ -n "${TMUX+set}" ]]; then
    tmux display-message -p "#S" | xargs printf '[tmux:%s]'
  elif [[ "$TERM" =~ ^screen.* ]]; then
    echo $STY | cut -d '.' -f1 | xargs printf '[screen:%s]'
  fi
}
