#!/bin/bash
#
#

alias ls='gls'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# copy/paste
alias copy='pbcopy'
alias paste='pbpaste'

# mac helpers
alias show="defaults write com.apple.Finder AppleShowAllFiles YES && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles NO && killall Finder"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update'
alias killaudio="sudo kill `ps -ax | grep 'coreaudiod' | grep 'sbin' |awk '{print $1}'`"
alias pdfmerge="/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py --output output.pdf "
# alias free='ruby $BASH_DIR/scripts/free-memory.rb'

# Quick way to rebuild the Launch Services database and get rid of duplicates in the Open With submenu.
alias lscleanup='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user | killall Finder'


# folders
# alias dev='cd ~/Dev'
# alias docs='cd ~/Dropbox/Documents'
# alias projects='cd ~/Dev/Projects'
alias dl='cd ~/Downloads'
alias dp='cd ~/Dropbox (Personal)'
