#!/bin/bash
#
#

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# parse_hg_bookmark() {
#   hg bookmark 2> /dev/null | awk '{print "(" $2 ")"}'
# }

export PS1="\n\[$(tput bold)\]\[$(tput setaf 5)\]➜ \[$(tput setaf 6)\]\w\[$(tput setaf 3)\]\$(parse_git_branch) \[$(tput sgr0)\]"

if [ $(which fortune) ]; then
  echo ""
  fortune
  echo ""
fi
