#!/bin/bash
#
#

export PATH="/usr/local/bin:/usr/local/sbin:~/buck/bin:$PATH"
export EDITOR=vim
export VISUAL=vim

# go
# export GOPATH=$HOME/Dev/go
# export PATH=$PATH:$GOPATH/bin

# jvm
# export MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled"
export M2_HOME="/usr/local/Cellar/maven/3.3.9"
