#!/bin/bash
#
#

# export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# go
# export GOPATH=$HOME/Dev/go
# export PATH=$PATH:$GOPATH/bin

# jvm
# export MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled"
